#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

cd / || exit 1

s6-setuidgid striparr /usr/bin/gunicorn \
  --bind 0.0.0.0:40000 \
  --timeout 600 \
  striparr:app \
  2>&1 | awk '{print "[listener] " $0}'
