#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

cd / || exit 1

s6-setuidgid striparr gunicorn3 \
  --bind 0.0.0.0:40000 \
  --timeout 600 \
  --log-level info \
  striparr:app \
  2>&1 | awk -W Interactive '{print "[listener] " $0}'
