#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

cd / || exit 1

s6-setuidgid striparr /usr/bin/celery \
  --no-color \
  -A \
  striparr.celery \
  worker \
  --loglevel=WARNING \
  --concurrency 1 \
  2>&1 | awk '{print "[worker] " $0}'
