#!/usr/bin/with-contenv bash
#shellcheck shell=bash

PGID=${PGID:-1000}
PUID=${PUID:-1000}

# Set up timezone
if [ -z "${TZ}" ]; then
  echo -ne "\e[33m"
  echo "WARNING: TZ environment variable not set"
  echo -ne "\e[0m"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime > /dev/null 2>&1
  echo "$TZ" > /etc/timezone
fi

groupadd \
  --gid "${PGID}" \
  striparr \
  || true

useradd \
  --gid "${PGID}" \
  --uid "${PUID}" \
  --home-dir "/home/striparr" \
  --no-user-group \
  --system \
  striparr \
  || true

# Sanity check alert
EXITCODE=0
if [[ -n "$ALERT_EMAIL_ENABLE" ]]; then
  if [[ -z "$ALERT_EMAIL_TO" ]]; then
    echo "ERROR: If email alerts are enabled, you must set ALERT_EMAIL_TO."
    EXITCODE=1
  fi
  if [[ -z "$ALERT_EMAIL_FROM" ]]; then
    echo "ERROR: If email alerts are enabled, you must set ALERT_EMAIL_FROM."
    EXITCODE=1
  fi
  if [[ -z "$ALERT_EMAIL_SMTP_HOST" ]]; then
    echo "ERROR: If email alerts are enabled, you must set ALERT_EMAIL_SMTP_HOST."
    EXITCODE=1
  fi
  if [[ -z "$ALERT_EMAIL_SMTP_PORT" ]]; then
    echo "ERROR: If email alerts are enabled, you must set ALERT_EMAIL_SMTP_PORT."
    EXITCODE=1
  fi
fi

# Exit if problems
exit "$EXITCODE"