name: Tests

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test-build:
    name: Test
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/build_and_push_image.yml@main
    with:
      push_enabled: false
      get_version_method: git_commit_hash_short
