#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

cd / || exit 1

s6-setuidgid striparr celery \
  --no-color \
  -A \
  striparr.celery \
  worker \
  --loglevel=INFO \
  --concurrency 1 \
  --without-mingle \
  2>&1 | awk -W Interactive '{print "[worker] " $0}'
